import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "../components/Footer";
import Navbar from "@/components/nav/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import createSupabaseServer from "@/lib/supabase/server";
import InitUser from "@/components/store/InitUser";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// TODO: removet this
	const supabase = await createSupabaseServer();
	const { data } = await supabase.auth.getUser();

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${inter.className} bg-[#09090B] text-gray-200 antialiased  py-10`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<main className="flex flex-col max-w-7xl mx-auto min-h-screen space-y-10 p-5">
						<Navbar user={data.user} />
						<div className="w-full flex-1 ">{children}</div>
						<Footer />
					</main>

					<Toaster position="top-center" reverseOrder={false} />
				</ThemeProvider>
				<InitUser user={data.user} />
			</body>
		</html>
	);
}
